#cloud-config
groups:
  - docker
users:
  - name: username
    groups: wheel, docker
    shell: /bin/zsh
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIKEvgAdTE2JaIv9FlCy8shNM6rFtb6goLNoqvLfEThpruD3OoAU94YWnQP8ScuLbIUHJdzxsC9tiIAjgh0+m99XAL3DBOdi7IFVEQt71lw9w8n3D0HvG765UzCDdbgZolAI/FGiJzUDYIG8Hz0ol1LAFqtyRpaFsp6vZtq68PBkqkuTUwIss4QP9LyDjdjfeAR17rEVxtpukBdecKsCuynAy8QqnONE0lEukHwMRBkMywAD462W3uEfmsYuQFvG+hPuReqQFJmhM1e4verdoU8r3Uu5flQ5YbgqSh5KGunqBvYCyYtEwCcEG5uKTRRKvEZttBaK3PkAJq5mK9IMcqg4XyPlqcMzn962AgCcV5WlECvmQ/sN4L12Boh6Zf4A2d8EnE1XxyCt4YXJ9wOat9gwt77TK0Mf11fWpFEouN6eWOAW4fBle3H9plFa6vR8hrHqWfeWYA+UrrguZaR020gTyzBYCfGYMqwL2UfMpQQIyivnYcmjS+l4EM39MBwOk= quentin@dell
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBwdgAhpGS8oJiZtJo0eyK4blE8BBtpl7f7Dr2EJkQLHcv0X23jniT1K7yJAA2XWV7VDGbWmQbUDHKP35fT97szAqzPjeWKeoUbLwHUTkETeaUqdYrkgcVZHjWqRGflvD3giip3fRzv+1Kp9AlH+gni/lppC4AZ0VavR0AUfPVRCcT97xA/AjOD7qngGi3faBBt9bwmHTeUBzvft4DLP8GDQsW9e4N5UHFj2DSRF6nI1FCAFRlUKPV+YPDOWD7Di26pANsVrY0VmH8f0DTOp8UCNH229aOK/TVIDL0dLNcIpFiHoIYRYe4TRjovm29NhZfqJ6ezf4moRCtnMBNegXb quentin@hp
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCxza1Ci7bXy8s7vQIObxbBn+npWVcd4dwXeUHOU1s/vmz+kaNxJbrzPT3FsAzCB/AkLWe7DUjOB9dQ60hwCvFCOHIKKz+MIm857oBJ3hsyPSI1P/NNz22tUNiPLXhOcHwr/hBi6L3z4+/FpXHDZ3TLkGy29PXrTxUbcQCS7C/n0SdL8FPV39agz6//QMKNv57eY1rtFL2aQp5b8YCpDuHICcSBqsKiQqeuZQ8YKlWF0PKYnV5gaQ7QN65iDO+HFcs5B0TPCStu8fUMMPgr/pXEzWY9UVnM4HfBTURjiNYQ1MCeZjZHfe0zlId7EEvLBVrOxZVspQgd3ml6njM/IWDYteDe572fFRFjsVbhZddNH3Mz3jLtSW2adFQ3oAQtxkhqbNcc2rAgyzs7p8Xn59FY1bAH2dIaL5mgCmjshFrV/fjpa0GTsdPMJrPDze0XDnlE35xdF/bKd85n2sDIarSaQvwBxzNy3NuzXVoNTJh6OZtXT2eVBl4g1gDKefZ2s+0= bot@travis-ci
runcmd:
  - curl -sSL https://repos.insights.digitalocean.com/install.sh | sudo bash
  - yum install -y yum-utils
  - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  - yum install -y docker-ce docker-ce-cli containerd.io
  - systemctl enable docker
  - curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - export ZSH="/home/username/.oh-my-zsh" && sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  - git clone https://github.com/zsh-users/zsh-completions /home/username/.oh-my-zsh/custom/plugins/zsh-completions
  - git clone https://github.com/quentinburgniard/reverse-proxy.git /home/username/reverse-proxy
  - cp /home/username/.oh-my-zsh/templates/zshrc.zsh-template /home/username/.zshrc
  - sed -i 's/^plugins.*/plugins=(git zsh-completions docker docker-compose)/' /home/username/.zshrc
  - chown -R username:username /home/username/
  - echo 'AllowUsers username' >> /etc/ssh/sshd_config
  - echo 'PermitRootLogin no' >> /etc/ssh/sshd_config
  - systemctl reload sshd.service
packages:
  - git
  - zsh
package_upgrade: true
power_state:
  mode: reboot