#cloud-config
groups:
  - docker


users:
  - name: tubercule
    groups: wheel, docker
    shell: /bin/zsh
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDK+0ctdpwuhBLGffOhwmK0G2+UMfoXK0jBgsxBWt8ximcU8/icsOcjwEYwbJhEqgMYPARVvqTxJW6EKL/q483lpwvtyVhJP+wH53eQTMddHJXmV9/edrE/sUDUURxVzVk1tPaCeFwPd/y6+QzFRCa6fYfTyvUN/h9KoqiTScDoE4DqPJjDlE9xADCkLYq2G9qHSL/388T9VTOtrNWEMzw6N6jA9IOQXX/blNe6FGaeBnPdmGaxbXtPlIB3D0jxRk33K7ihBUTeyuxapAcn4y9v8S99YG4esGulYZgTb4TYsEPgAdUdlQ/w3U+GPQZu5BSfOqKaorfo1pLpeTDDdNr9 quentin@acer-swift


runcmd:
  # https://www.digitalocean.com/docs/monitoring/quickstart/
  - curl -sSL https://insights.nyc3.cdn.digitaloceanspaces.com/install.sh | sudo bash


  # https://docs.docker.com/install/linux/docker-ce/centos/
  - yum install -y yum-utils device-mapper-persistent-data lvm2
  - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  - yum install -y docker-ce
  - systemctl enable docker


  # https://docs.docker.com/compose/install/#install-compose
  - curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose


  # https://github.com/robbyrussell/oh-my-zsh
  - export ZSH="/home/tubercule/.oh-my-zsh" && sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"


  # https://github.com/zsh-users/zsh-completions#oh-my-zsh
  - git clone https://github.com/zsh-users/zsh-completions /home/tubercule/.oh-my-zsh/custom/plugins/zsh-completions


  - cp /home/tubercule/.oh-my-zsh/templates/zshrc.zsh-template /home/tubercule/.zshrc
  - sed -i 's/^plugins.*/plugins=(git zsh-completions docker docker-compose)/' /home/tubercule/.zshrc


  - chown -R tubercule:tubercule /home/tubercule/


  # https://www.digitalocean.com/community/tutorials/how-to-use-cloud-config-for-your-initial-server-setup
  - echo 'AllowUsers tubercule' >> /etc/ssh/sshd_config
  - echo 'PermitRootLogin no' >> /etc/ssh/sshd_config
  - systemctl reload sshd.service


packages:
  - git
  - zsh


package_upgrade: true


# https://cloudinit.readthedocs.io/en/latest/topics/examples.html#reboot-poweroff-when-finished
power_state:
  mode: reboot
