#cloud-config
users:
  - name: tubercule
    groups: wheel
    shell: /bin/zsh
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDK+0ctdpwuhBLGffOhwmK0G2+UMfoXK0jBgsxBWt8ximcU8/icsOcjwEYwbJhEqgMYPARVvqTxJW6EKL/q483lpwvtyVhJP+wH53eQTMddHJXmV9/edrE/sUDUURxVzVk1tPaCeFwPd/y6+QzFRCa6fYfTyvUN/h9KoqiTScDoE4DqPJjDlE9xADCkLYq2G9qHSL/388T9VTOtrNWEMzw6N6jA9IOQXX/blNe6FGaeBnPdmGaxbXtPlIB3D0jxRk33K7ihBUTeyuxapAcn4y9v8S99YG4esGulYZgTb4TYsEPgAdUdlQ/w3U+GPQZu5BSfOqKaorfo1pLpeTDDdNr9 quentin@acer-swift


# docker repository
# https://docs.docker.com/install/linux/docker-ce/centos/

yum_repos:
  docker:
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    gpgcheck: true
    gpgkey: 060A61C51B558A7F742B77AAC52FEB6B621E9F35
    name: Docker repository

packages:
  # docker
  - docker-ce

  # git
  - git

  # zsh
  - zsh
  - zsh-completion


package_upgrade: true


runcmd:
  # https://www.digitalocean.com/community/tutorials/how-to-use-cloud-config-for-your-initial-server-setup
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '$aAllowUsers tubercule' /etc/ssh/sshd_config
  - restart ssh

  # git config
  - git config --global user.name "Quentin Burgniard"
  - git config --global user.mail "quentinburgniard@gmail.com"

  # oh-my-zsh
  # https://github.com/robbyrussell/oh-my-zsh
  - sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"