#cloud-config
package_upgrade: true

users:
  - name: tubercule
    groups: wheel
    shell: /bin/zsh
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1+aK6CUIVZ/gq4gCOjnAbQJs6hj1rmnkfDR4VcHu7/H6ebdz+6wf3ypEzFIWV+xw3kSM/qeMxMdXd138yBM+xZYUYRFXx3k1LEi++1SCo/9CKSOeamlFShkG6vd80bM8MYzUKbHf9fvkIlOGR5P3zN9lgF9rqBDMY+qyK2OXKbBgeLaGMqcQG/zBpAt1pFyRgXihSA3ApoOaVA2ANpbQCDvRv7J0g8YF2ubuk00ZKvxInkzg1bheS1yiPnyc40teEsccx0OPw/vmTCxBdsp0fh6G+GvyBZJ7SnQtGHAoY+PXfqy6fvYUnkpJPiJ/FEbl6YRGpBMhp429geH3xlBuN quentin@acer-swift
    runcmd:
      - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
      - sed -i -e '$aAllowUsers tubercule' /etc/ssh/sshd_config
      - restart ssh